language: node_js

node_js:
  - "5.1"

before_install:
  - npm install -g gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar"
  - "java -jar selenium-server-standalone-2.53.1.jar > /dev/null &"

script:
  - gulp test-e2e
